// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorkGroup_RPGHelp.DAL.Contexts;

#nullable disable

namespace WorkGroup_RPGHelp.DAL.Migrations
{
    [DbContext(typeof(RPGHelpContext))]
    [Migration("20251217110407_AddSeedCampaign")]
    partial class AddSeedCampaign
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CampagnUsers", b =>
                {
                    b.Property<int>("CampagnsId")
                        .HasColumnType("int");

                    b.Property<int>("UsersId")
                        .HasColumnType("int");

                    b.HasKey("CampagnsId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("CampagnUsers");

                    b.HasData(
                        new
                        {
                            CampagnsId = 1,
                            UsersId = 1
                        },
                        new
                        {
                            CampagnsId = 2,
                            UsersId = 1
                        },
                        new
                        {
                            CampagnsId = 1,
                            UsersId = 2
                        });
                });

            modelBuilder.Entity("RaceSpell", b =>
                {
                    b.Property<int>("RacesId")
                        .HasColumnType("int");

                    b.Property<int>("SpellsId")
                        .HasColumnType("int");

                    b.HasKey("RacesId", "SpellsId");

                    b.HasIndex("SpellsId");

                    b.ToTable("RaceSpell");
                });

            modelBuilder.Entity("RoleUsers", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("RoleId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("RoleUsers");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            UserId = 1
                        },
                        new
                        {
                            RoleId = 2,
                            UserId = 1
                        },
                        new
                        {
                            RoleId = 2,
                            UserId = 2
                        },
                        new
                        {
                            RoleId = 2,
                            UserId = 3
                        },
                        new
                        {
                            RoleId = 1,
                            UserId = 4
                        },
                        new
                        {
                            RoleId = 2,
                            UserId = 4
                        });
                });

            modelBuilder.Entity("WorkGroup_RPGHelp.DL.Entities.BonusRacial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BonusName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("BonusValue")
                        .HasColumnType("int");

                    b.Property<string>("MalusName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MalusValue")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("BonusRacial", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BonusName = "Dexterity",
                            BonusValue = 2,
                            MalusName = "Strength",
                            MalusValue = -2
                        },
                        new
                        {
                            Id = 2,
                            BonusName = "Intelligence",
                            BonusValue = 2,
                            MalusName = "Wisdom",
                            MalusValue = -2
                        },
                        new
                        {
                            Id = 3,
                            BonusName = "Constitution",
                            BonusValue = 2,
                            MalusName = "Charisma",
                            MalusValue = -2
                        },
                        new
                        {
                            Id = 4,
                            BonusName = "Strength",
                            BonusValue = 2,
                            MalusName = "Intelligence",
                            MalusValue = -2
                        },
                        new
                        {
                            Id = 5,
                            BonusName = "Wisdom",
                            BonusValue = 2,
                            MalusName = "Dexterity",
                            MalusValue = -2
                        },
                        new
                        {
                            Id = 6,
                            BonusName = "Charisma",
                            BonusValue = 2,
                            MalusName = "Constitution",
                            MalusValue = -2
                        },
                        new
                        {
                            Id = 7,
                            BonusName = "Dexterity",
                            BonusValue = 2,
                            MalusName = "Charisma",
                            MalusValue = -2
                        },
                        new
                        {
                            Id = 8,
                            BonusName = "Strength",
                            BonusValue = 2,
                            MalusName = "Wisdom",
                            MalusValue = -2
                        },
                        new
                        {
                            Id = 9,
                            BonusName = "Intelligence",
                            BonusValue = 2,
                            MalusName = "Strength",
                            MalusValue = -2
                        },
                        new
                        {
                            Id = 10,
                            BonusName = "Constitution",
                            BonusValue = 2,
                            MalusName = "Dexterity",
                            MalusValue = -2
                        },
                        new
                        {
                            Id = 11,
                            BonusName = "Wisdom",
                            BonusValue = 2,
                            MalusName = "Charisma",
                            MalusValue = -2
                        },
                        new
                        {
                            Id = 12,
                            BonusName = "Charisma",
                            BonusValue = 2,
                            MalusName = "Strength",
                            MalusValue = -2
                        },
                        new
                        {
                            Id = 13,
                            BonusName = "Intelligence",
                            BonusValue = 2,
                            MalusName = "Constitution",
                            MalusValue = -2
                        },
                        new
                        {
                            Id = 14,
                            BonusName = "Strength",
                            BonusValue = 2,
                            MalusName = "Dexterity",
                            MalusValue = -2
                        },
                        new
                        {
                            Id = 15,
                            BonusName = "Dexterity",
                            BonusValue = 2,
                            MalusName = "Intelligence",
                            MalusValue = -2
                        },
                        new
                        {
                            Id = 16,
                            BonusName = "Constitution",
                            BonusValue = 2,
                            MalusName = "Wisdom",
                            MalusValue = -2
                        },
                        new
                        {
                            Id = 17,
                            BonusName = "Wisdom",
                            BonusValue = 2,
                            MalusName = "Strength",
                            MalusValue = -2
                        },
                        new
                        {
                            Id = 18,
                            BonusName = "Charisma",
                            BonusValue = 2,
                            MalusName = "Intelligence",
                            MalusValue = -2
                        },
                        new
                        {
                            Id = 19,
                            BonusName = "Strength",
                            BonusValue = 2,
                            MalusName = "Constitution",
                            MalusValue = -2
                        },
                        new
                        {
                            Id = 20,
                            BonusName = "Dexterity",
                            BonusValue = 2,
                            MalusName = "Wisdom",
                            MalusValue = -2
                        },
                        new
                        {
                            Id = 21,
                            BonusName = "Intelligence",
                            BonusValue = 2,
                            MalusName = "Charisma",
                            MalusValue = -2
                        },
                        new
                        {
                            Id = 22,
                            BonusName = "Constitution",
                            BonusValue = 2,
                            MalusName = "Strength",
                            MalusValue = -2
                        },
                        new
                        {
                            Id = 23,
                            BonusName = "Wisdom",
                            BonusValue = 2,
                            MalusName = "Intelligence",
                            MalusValue = -2
                        });
                });

            modelBuilder.Entity("WorkGroup_RPGHelp.DL.Entities.Campagn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdGM")
                        .HasColumnType("int");

                    b.Property<bool>("IsFinish")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Campagn", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Chapter 4 finished",
                            IdGM = 1,
                            IsFinish = false,
                            Name = "Ma première Campagne"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Chapter 2 started",
                            IdGM = 2,
                            IsFinish = false,
                            Name = "True Story"
                        },
                        new
                        {
                            Id = 3,
                            IdGM = 1,
                            IsFinish = false,
                            Name = "Dragon First"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Exploration du château de Strahd",
                            IdGM = 3,
                            IsFinish = false,
                            Name = "L'Ombre de Ravenloft"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Campagne d'introduction terminée",
                            IdGM = 4,
                            IsFinish = true,
                            Name = "Les Mines de Phandalin"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Chapitre 3 : En route vers Baldur's Gate",
                            IdGM = 1,
                            IsFinish = false,
                            Name = "Le Trésor de la Reine Dragon"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Groupe décimé au chapitre 5",
                            IdGM = 2,
                            IsFinish = true,
                            Name = "La Malédiction de Strahd"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Fuite des drows réussie",
                            IdGM = 3,
                            IsFinish = false,
                            Name = "Odyssée dans l'Outreterre"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Bloqués dans la jungle de Chult",
                            IdGM = 4,
                            IsFinish = false,
                            Name = "Le Tombeau de l'Annihilation"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Bataille finale imminente",
                            IdGM = 1,
                            IsFinish = false,
                            Name = "L'Ascension de Tiamat"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Enquête urbaine en cours",
                            IdGM = 2,
                            IsFinish = false,
                            Name = "Waterdeep : Le Vol des Dragons"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Voyage en enfer",
                            IdGM = 3,
                            IsFinish = false,
                            Name = "Descente en Avernus"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Série de donjons one-shot",
                            IdGM = 4,
                            IsFinish = true,
                            Name = "Les Contes du Portail Béant"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Survie dans le grand nord",
                            IdGM = 1,
                            IsFinish = false,
                            Name = "Le Froid d'Icewind Dale"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Mystère antique",
                            IdGM = 2,
                            IsFinish = false,
                            Name = "La Citadelle de Verre"
                        },
                        new
                        {
                            Id = 16,
                            Description = "Guerre contre les géants de feu",
                            IdGM = 3,
                            IsFinish = false,
                            Name = "L'Héritage des Géants"
                        },
                        new
                        {
                            Id = 17,
                            Description = "Aventure maritime",
                            IdGM = 4,
                            IsFinish = false,
                            Name = "Les Pirates de la Côte des Épées"
                        },
                        new
                        {
                            Id = 18,
                            Description = "Horreur cosmique",
                            IdGM = 1,
                            IsFinish = true,
                            Name = "Le Réveil de l'Ancien"
                        },
                        new
                        {
                            Id = 19,
                            Description = "Intrigue politique et trains-éclairs",
                            IdGM = 2,
                            IsFinish = false,
                            Name = "Les Éclats d'Eberron"
                        },
                        new
                        {
                            Id = 20,
                            Description = "Quête pour les artefacts",
                            IdGM = 3,
                            IsFinish = false,
                            Name = "La Prophétie de l'Oracle"
                        },
                        new
                        {
                            Id = 21,
                            Description = "Donjon classique",
                            IdGM = 4,
                            IsFinish = false,
                            Name = "Sous la Montagne de Feu"
                        },
                        new
                        {
                            Id = 22,
                            Description = "Défense de la ville terminée",
                            IdGM = 1,
                            IsFinish = true,
                            Name = "Le Siège de Neverwinter"
                        },
                        new
                        {
                            Id = 23,
                            Description = "Suite d'Avernus",
                            IdGM = 2,
                            IsFinish = false,
                            Name = "L'Hérésie de Zariel"
                        },
                        new
                        {
                            Id = 24,
                            Description = "Rencontre avec les Dryades",
                            IdGM = 3,
                            IsFinish = false,
                            Name = "La Forêt des Murmures"
                        },
                        new
                        {
                            Id = 25,
                            Description = "Académie de magie en péril",
                            IdGM = 4,
                            IsFinish = false,
                            Name = "Le Secret des Arcanes"
                        },
                        new
                        {
                            Id = 26,
                            Description = "Chasse au trésor céleste",
                            IdGM = 1,
                            IsFinish = false,
                            Name = "Le Vol du Phénix"
                        },
                        new
                        {
                            Id = 27,
                            Description = "Campagne nostalgique terminée",
                            IdGM = 2,
                            IsFinish = true,
                            Name = "Les Chroniques de Greyhawk"
                        },
                        new
                        {
                            Id = 28,
                            Description = "Exploration de cité perdue",
                            IdGM = 3,
                            IsFinish = false,
                            Name = "La Ruine d'Omu"
                        },
                        new
                        {
                            Id = 29,
                            Description = "Invocations incontrôlées",
                            IdGM = 4,
                            IsFinish = false,
                            Name = "La Colère des Éléments"
                        },
                        new
                        {
                            Id = 30,
                            Description = "Scénario d'une soirée",
                            IdGM = 1,
                            IsFinish = true,
                            Name = "Le Festin des Gobelins"
                        },
                        new
                        {
                            Id = 31,
                            Description = "Niveau 5 atteint",
                            IdGM = 2,
                            IsFinish = false,
                            Name = "La Tour du Mage Fou"
                        },
                        new
                        {
                            Id = 32,
                            Description = "Aventure dans le désert",
                            IdGM = 3,
                            IsFinish = false,
                            Name = "L'Oasis de Diamant"
                        },
                        new
                        {
                            Id = 33,
                            Description = "Horreur rurale",
                            IdGM = 4,
                            IsFinish = false,
                            Name = "Les Sombres Adrets"
                        });
                });

            modelBuilder.Entity("WorkGroup_RPGHelp.DL.Entities.Charactere", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BaseAttackBonus")
                        .HasColumnType("int");

                    b.Property<int?>("CampagnId")
                        .HasColumnType("int");

                    b.Property<int>("Charisma")
                        .HasColumnType("int");

                    b.Property<int>("Constitution")
                        .HasColumnType("int");

                    b.Property<int>("Defence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(10);

                    b.Property<int>("Dexterity")
                        .HasColumnType("int");

                    b.Property<int>("FortitudeSave")
                        .HasColumnType("int");

                    b.Property<int>("Initiative")
                        .HasColumnType("int");

                    b.Property<int>("Intelligence")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PVCurrent")
                        .HasColumnType("int");

                    b.Property<int>("PVMax")
                        .HasColumnType("int");

                    b.Property<int>("RaceId")
                        .HasColumnType("int");

                    b.Property<int>("ReflexeSave")
                        .HasColumnType("int");

                    b.Property<int>("Speed")
                        .HasColumnType("int");

                    b.Property<int>("Strength")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("WillpowerSave")
                        .HasColumnType("int");

                    b.Property<int>("Wisdom")
                        .HasColumnType("int");

                    b.Property<int>("XP")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CampagnId");

                    b.HasIndex("RaceId");

                    b.HasIndex("UserId");

                    b.ToTable("Characteres", null, t =>
                        {
                            t.HasCheckConstraint("CK_Charactere__Charisma", "Charisma >= 0");

                            t.HasCheckConstraint("CK_Charactere__Constitution", "Constitution >= 0");

                            t.HasCheckConstraint("CK_Charactere__Dexterity", "Dexterity >= 0");

                            t.HasCheckConstraint("CK_Charactere__Intelligence", "Intelligence >= 0");

                            t.HasCheckConstraint("CK_Charactere__Level", "Level >= 0");

                            t.HasCheckConstraint("CK_Charactere__PVMax", "PVMax > 0");

                            t.HasCheckConstraint("CK_Charactere__Speed", "Speed >= 0");

                            t.HasCheckConstraint("CK_Charactere__Strength", "Strength >= 0");

                            t.HasCheckConstraint("CK_Charactere__Wisdom", "Wisdom >= 0");

                            t.HasCheckConstraint("CK_Charactere__XP", "XP >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaseAttackBonus = 1,
                            CampagnId = 1,
                            Charisma = 10,
                            Constitution = 14,
                            Defence = 17,
                            Dexterity = 10,
                            FortitudeSave = 4,
                            Initiative = 1,
                            Intelligence = 8,
                            Level = 1,
                            Name = "Arik le Solide",
                            PVCurrent = 12,
                            PVMax = 12,
                            RaceId = 1,
                            ReflexeSave = 0,
                            Speed = 30,
                            Strength = 16,
                            UserId = 1,
                            WillpowerSave = 1,
                            Wisdom = 12,
                            XP = 0
                        },
                        new
                        {
                            Id = 2,
                            BaseAttackBonus = 1,
                            CampagnId = 1,
                            Charisma = 8,
                            Constitution = 12,
                            Defence = 15,
                            Dexterity = 18,
                            FortitudeSave = 1,
                            Initiative = 4,
                            Intelligence = 10,
                            Level = 1,
                            Name = "Elara la Furtive",
                            PVCurrent = 10,
                            PVMax = 10,
                            RaceId = 2,
                            ReflexeSave = 6,
                            Speed = 30,
                            Strength = 10,
                            UserId = 2,
                            WillpowerSave = 2,
                            Wisdom = 14,
                            XP = 1
                        },
                        new
                        {
                            Id = 3,
                            BaseAttackBonus = 1,
                            CampagnId = 2,
                            Charisma = 8,
                            Constitution = 16,
                            Defence = 16,
                            Dexterity = 12,
                            FortitudeSave = 5,
                            Initiative = 1,
                            Intelligence = 10,
                            Level = 1,
                            Name = "Borin Pied-de-Fer",
                            PVCurrent = 14,
                            PVMax = 14,
                            RaceId = 3,
                            ReflexeSave = 1,
                            Speed = 20,
                            Strength = 14,
                            UserId = 1,
                            WillpowerSave = 1,
                            Wisdom = 10,
                            XP = 1
                        },
                        new
                        {
                            Id = 4,
                            BaseAttackBonus = 1,
                            CampagnId = 1,
                            Charisma = 13,
                            Constitution = 12,
                            Defence = 12,
                            Dexterity = 12,
                            FortitudeSave = 1,
                            Initiative = 1,
                            Intelligence = 14,
                            Level = 1,
                            Name = "Valerius le Sage",
                            PVCurrent = 9,
                            PVMax = 9,
                            RaceId = 15,
                            ReflexeSave = 1,
                            Speed = 30,
                            Strength = 8,
                            UserId = 3,
                            WillpowerSave = 5,
                            Wisdom = 18,
                            XP = 1
                        },
                        new
                        {
                            Id = 5,
                            BaseAttackBonus = 1,
                            CampagnId = 1,
                            Charisma = 15,
                            Constitution = 14,
                            Defence = 16,
                            Dexterity = 12,
                            FortitudeSave = 4,
                            Initiative = 1,
                            Intelligence = 7,
                            Level = 1,
                            Name = "Zog l'Éclatant",
                            PVCurrent = 13,
                            PVMax = 13,
                            RaceId = 6,
                            ReflexeSave = 1,
                            Speed = 30,
                            Strength = 18,
                            UserId = 4,
                            WillpowerSave = 2,
                            Wisdom = 10,
                            XP = 1
                        },
                        new
                        {
                            Id = 6,
                            BaseAttackBonus = 1,
                            CampagnId = 2,
                            Charisma = 14,
                            Constitution = 10,
                            Defence = 13,
                            Dexterity = 16,
                            FortitudeSave = 1,
                            Initiative = 3,
                            Intelligence = 18,
                            Level = 1,
                            Name = "Lirael de la Rose",
                            PVCurrent = 8,
                            PVMax = 8,
                            RaceId = 1,
                            ReflexeSave = 3,
                            Speed = 30,
                            Strength = 7,
                            UserId = 2,
                            WillpowerSave = 4,
                            Wisdom = 12,
                            XP = 1
                        },
                        new
                        {
                            Id = 7,
                            BaseAttackBonus = 2,
                            CampagnId = 2,
                            Charisma = 7,
                            Constitution = 18,
                            Defence = 15,
                            Dexterity = 13,
                            FortitudeSave = 6,
                            Initiative = 1,
                            Intelligence = 8,
                            Level = 2,
                            Name = "Thokk le Briseur",
                            PVCurrent = 15,
                            PVMax = 15,
                            RaceId = 9,
                            ReflexeSave = 1,
                            Speed = 30,
                            Strength = 17,
                            UserId = 3,
                            WillpowerSave = 1,
                            Wisdom = 9,
                            XP = 1200
                        },
                        new
                        {
                            Id = 8,
                            BaseAttackBonus = 1,
                            Charisma = 13,
                            Constitution = 12,
                            Defence = 14,
                            Dexterity = 19,
                            FortitudeSave = 1,
                            Initiative = 4,
                            Intelligence = 11,
                            Level = 1,
                            Name = "Faelar Vent-Léger",
                            PVCurrent = 11,
                            PVMax = 11,
                            RaceId = 10,
                            ReflexeSave = 5,
                            Speed = 40,
                            Strength = 10,
                            UserId = 4,
                            WillpowerSave = 2,
                            Wisdom = 14,
                            XP = 500
                        },
                        new
                        {
                            Id = 9,
                            BaseAttackBonus = 2,
                            CampagnId = 2,
                            Charisma = 8,
                            Constitution = 17,
                            Defence = 18,
                            Dexterity = 11,
                            FortitudeSave = 5,
                            Initiative = 1,
                            Intelligence = 9,
                            Level = 2,
                            Name = "Grimm de Pierre",
                            PVCurrent = 18,
                            PVMax = 22,
                            RaceId = 4,
                            ReflexeSave = 1,
                            Speed = 20,
                            Strength = 15,
                            UserId = 2,
                            WillpowerSave = 3,
                            Wisdom = 13,
                            XP = 1500
                        },
                        new
                        {
                            Id = 10,
                            BaseAttackBonus = 1,
                            CampagnId = 3,
                            Charisma = 16,
                            Constitution = 13,
                            Defence = 15,
                            Dexterity = 18,
                            FortitudeSave = 2,
                            Initiative = 4,
                            Intelligence = 12,
                            Level = 1,
                            Name = "Sly l'Ombre",
                            PVCurrent = 9,
                            PVMax = 9,
                            RaceId = 5,
                            ReflexeSave = 6,
                            Speed = 25,
                            Strength = 9,
                            UserId = 1,
                            WillpowerSave = 1,
                            Wisdom = 10,
                            XP = 1
                        },
                        new
                        {
                            Id = 11,
                            BaseAttackBonus = 1,
                            CampagnId = 3,
                            Charisma = 12,
                            Constitution = 14,
                            Defence = 12,
                            Dexterity = 14,
                            FortitudeSave = 2,
                            Initiative = 2,
                            Intelligence = 17,
                            Level = 1,
                            Name = "Mala la Rouge",
                            PVCurrent = 10,
                            PVMax = 10,
                            RaceId = 21,
                            ReflexeSave = 2,
                            Speed = 30,
                            Strength = 10,
                            UserId = 2,
                            WillpowerSave = 4,
                            Wisdom = 11,
                            XP = 1
                        },
                        new
                        {
                            Id = 12,
                            BaseAttackBonus = 1,
                            CampagnId = 3,
                            Charisma = 9,
                            Constitution = 15,
                            Defence = 17,
                            Dexterity = 8,
                            FortitudeSave = 4,
                            Initiative = 1,
                            Intelligence = 10,
                            Level = 1,
                            Name = "Korg l'Ancien",
                            PVCurrent = 14,
                            PVMax = 14,
                            RaceId = 23,
                            ReflexeSave = 1,
                            Speed = 20,
                            Strength = 14,
                            UserId = 3,
                            WillpowerSave = 5,
                            Wisdom = 16,
                            XP = 1
                        },
                        new
                        {
                            Id = 13,
                            BaseAttackBonus = 1,
                            CampagnId = 3,
                            Charisma = 18,
                            Constitution = 12,
                            Defence = 13,
                            Dexterity = 15,
                            FortitudeSave = 1,
                            Initiative = 2,
                            Intelligence = 13,
                            Level = 1,
                            Name = "Vesper",
                            PVCurrent = 12,
                            PVMax = 12,
                            RaceId = 8,
                            ReflexeSave = 3,
                            Speed = 30,
                            Strength = 11,
                            UserId = 4,
                            WillpowerSave = 4,
                            Wisdom = 10,
                            XP = 1
                        },
                        new
                        {
                            Id = 14,
                            BaseAttackBonus = 1,
                            CampagnId = 3,
                            Charisma = 10,
                            Constitution = 16,
                            Defence = 16,
                            Dexterity = 12,
                            FortitudeSave = 5,
                            Initiative = 1,
                            Intelligence = 8,
                            Level = 1,
                            Name = "Orik du Pic",
                            PVCurrent = 16,
                            PVMax = 16,
                            RaceId = 12,
                            ReflexeSave = 1,
                            Speed = 30,
                            Strength = 19,
                            UserId = 1,
                            WillpowerSave = 1,
                            Wisdom = 11,
                            XP = 1
                        },
                        new
                        {
                            Id = 15,
                            BaseAttackBonus = 1,
                            CampagnId = 3,
                            Charisma = 11,
                            Constitution = 12,
                            Defence = 12,
                            Dexterity = 14,
                            FortitudeSave = 1,
                            Initiative = 2,
                            Intelligence = 19,
                            Level = 1,
                            Name = "Nalia l'Astucieuse",
                            PVCurrent = 8,
                            PVMax = 8,
                            RaceId = 7,
                            ReflexeSave = 2,
                            Speed = 25,
                            Strength = 8,
                            UserId = 2,
                            WillpowerSave = 3,
                            Wisdom = 13,
                            XP = 1
                        },
                        new
                        {
                            Id = 16,
                            BaseAttackBonus = 1,
                            CampagnId = 3,
                            Charisma = 8,
                            Constitution = 11,
                            Defence = 14,
                            Dexterity = 17,
                            FortitudeSave = 1,
                            Initiative = 3,
                            Intelligence = 14,
                            Level = 1,
                            Name = "Skree",
                            PVCurrent = 9,
                            PVMax = 9,
                            RaceId = 13,
                            ReflexeSave = 5,
                            Speed = 30,
                            Strength = 10,
                            UserId = 3,
                            WillpowerSave = 2,
                            Wisdom = 15,
                            XP = 1
                        },
                        new
                        {
                            Id = 17,
                            BaseAttackBonus = 2,
                            CampagnId = 3,
                            Charisma = 9,
                            Constitution = 15,
                            Defence = 15,
                            Dexterity = 14,
                            FortitudeSave = 4,
                            Initiative = 2,
                            Intelligence = 7,
                            Level = 2,
                            Name = "Borg l'Étourdi",
                            PVCurrent = 18,
                            PVMax = 18,
                            RaceId = 17,
                            ReflexeSave = 3,
                            Speed = 30,
                            Strength = 18,
                            UserId = 4,
                            WillpowerSave = 1,
                            Wisdom = 8,
                            XP = 1100
                        },
                        new
                        {
                            Id = 18,
                            BaseAttackBonus = 1,
                            CampagnId = 3,
                            Charisma = 17,
                            Constitution = 12,
                            Defence = 14,
                            Dexterity = 12,
                            FortitudeSave = 3,
                            Initiative = 1,
                            Intelligence = 11,
                            Level = 1,
                            Name = "Sarya la Pure",
                            PVCurrent = 10,
                            PVMax = 10,
                            RaceId = 15,
                            ReflexeSave = 1,
                            Speed = 30,
                            Strength = 12,
                            UserId = 1,
                            WillpowerSave = 5,
                            Wisdom = 15,
                            XP = 200
                        },
                        new
                        {
                            Id = 19,
                            BaseAttackBonus = 1,
                            CampagnId = 3,
                            Charisma = 15,
                            Constitution = 13,
                            Defence = 12,
                            Dexterity = 14,
                            FortitudeSave = 1,
                            Initiative = 2,
                            Intelligence = 18,
                            Level = 1,
                            Name = "Xil",
                            PVCurrent = 11,
                            PVMax = 11,
                            RaceId = 19,
                            ReflexeSave = 2,
                            Speed = 30,
                            Strength = 11,
                            UserId = 2,
                            WillpowerSave = 4,
                            Wisdom = 12,
                            XP = 1
                        },
                        new
                        {
                            Id = 20,
                            BaseAttackBonus = 3,
                            CampagnId = 3,
                            Charisma = 10,
                            Constitution = 18,
                            Defence = 19,
                            Dexterity = 10,
                            FortitudeSave = 7,
                            Initiative = 1,
                            Intelligence = 10,
                            Level = 3,
                            Name = "Durgan le Hardi",
                            PVCurrent = 28,
                            PVMax = 28,
                            RaceId = 4,
                            ReflexeSave = 2,
                            Speed = 20,
                            Strength = 16,
                            UserId = 3,
                            WillpowerSave = 4,
                            Wisdom = 12,
                            XP = 3000
                        },
                        new
                        {
                            Id = 21,
                            BaseAttackBonus = 1,
                            CampagnId = 3,
                            Charisma = 12,
                            Constitution = 14,
                            Defence = 14,
                            Dexterity = 11,
                            FortitudeSave = 4,
                            Initiative = 1,
                            Intelligence = 10,
                            Level = 1,
                            Name = "Luth l'Errant",
                            PVCurrent = 13,
                            PVMax = 13,
                            RaceId = 11,
                            ReflexeSave = 1,
                            Speed = 30,
                            Strength = 15,
                            UserId = 4,
                            WillpowerSave = 5,
                            Wisdom = 17,
                            XP = 1
                        },
                        new
                        {
                            Id = 22,
                            BaseAttackBonus = 1,
                            CampagnId = 3,
                            Charisma = 12,
                            Constitution = 10,
                            Defence = 15,
                            Dexterity = 18,
                            FortitudeSave = 1,
                            Initiative = 4,
                            Intelligence = 10,
                            Level = 1,
                            Name = "Meepo",
                            PVCurrent = 7,
                            PVMax = 7,
                            RaceId = 18,
                            ReflexeSave = 4,
                            Speed = 30,
                            Strength = 7,
                            UserId = 1,
                            WillpowerSave = 1,
                            Wisdom = 8,
                            XP = 50
                        },
                        new
                        {
                            Id = 23,
                            BaseAttackBonus = 2,
                            CampagnId = 3,
                            Charisma = 14,
                            Constitution = 13,
                            Defence = 16,
                            Dexterity = 20,
                            FortitudeSave = 2,
                            Initiative = 5,
                            Intelligence = 11,
                            Level = 2,
                            Name = "Zyrk l'Agile",
                            PVCurrent = 12,
                            PVMax = 12,
                            RaceId = 10,
                            ReflexeSave = 6,
                            Speed = 40,
                            Strength = 12,
                            UserId = 2,
                            WillpowerSave = 2,
                            Wisdom = 11,
                            XP = 1350
                        },
                        new
                        {
                            Id = 24,
                            BaseAttackBonus = 1,
                            CampagnId = 1,
                            Charisma = 8,
                            Constitution = 16,
                            Defence = 16,
                            Dexterity = 12,
                            FortitudeSave = 5,
                            Initiative = 1,
                            Intelligence = 8,
                            Level = 1,
                            Name = "Thokk le Briseur",
                            PVCurrent = 15,
                            PVMax = 15,
                            RaceId = 9,
                            ReflexeSave = 1,
                            Speed = 30,
                            Strength = 18,
                            UserId = 3,
                            WillpowerSave = 1,
                            Wisdom = 10,
                            XP = 1
                        },
                        new
                        {
                            Id = 25,
                            BaseAttackBonus = 1,
                            CampagnId = 2,
                            Charisma = 12,
                            Constitution = 12,
                            Defence = 13,
                            Dexterity = 14,
                            FortitudeSave = 1,
                            Initiative = 2,
                            Intelligence = 14,
                            Level = 1,
                            Name = "Lirael de l'Aube",
                            PVCurrent = 9,
                            PVMax = 9,
                            RaceId = 15,
                            ReflexeSave = 2,
                            Speed = 30,
                            Strength = 8,
                            UserId = 4,
                            WillpowerSave = 5,
                            Wisdom = 16,
                            XP = 1
                        },
                        new
                        {
                            Id = 26,
                            BaseAttackBonus = 1,
                            CampagnId = 3,
                            Charisma = 13,
                            Constitution = 12,
                            Defence = 13,
                            Dexterity = 15,
                            FortitudeSave = 1,
                            Initiative = 2,
                            Intelligence = 18,
                            Level = 1,
                            Name = "Gimble l'Inventeur",
                            PVCurrent = 8,
                            PVMax = 8,
                            RaceId = 7,
                            ReflexeSave = 3,
                            Speed = 25,
                            Strength = 6,
                            UserId = 1,
                            WillpowerSave = 2,
                            Wisdom = 10,
                            XP = 10
                        },
                        new
                        {
                            Id = 27,
                            BaseAttackBonus = 1,
                            Charisma = 14,
                            Constitution = 14,
                            Defence = 15,
                            Dexterity = 10,
                            FortitudeSave = 4,
                            Initiative = 1,
                            Intelligence = 10,
                            Level = 1,
                            Name = "Kriv l'Écaillé",
                            PVCurrent = 13,
                            PVMax = 13,
                            RaceId = 6,
                            ReflexeSave = 1,
                            Speed = 30,
                            Strength = 17,
                            UserId = 2,
                            WillpowerSave = 1,
                            Wisdom = 11,
                            XP = 1
                        },
                        new
                        {
                            Id = 28,
                            BaseAttackBonus = 1,
                            CampagnId = 2,
                            Charisma = 17,
                            Constitution = 12,
                            Defence = 14,
                            Dexterity = 16,
                            FortitudeSave = 1,
                            Initiative = 3,
                            Intelligence = 13,
                            Level = 1,
                            Name = "Zariel l'Ombre",
                            PVCurrent = 10,
                            PVMax = 10,
                            RaceId = 8,
                            ReflexeSave = 4,
                            Speed = 30,
                            Strength = 10,
                            UserId = 3,
                            WillpowerSave = 2,
                            Wisdom = 8,
                            XP = 1
                        },
                        new
                        {
                            Id = 29,
                            BaseAttackBonus = 1,
                            CampagnId = 3,
                            Charisma = 9,
                            Constitution = 15,
                            Defence = 14,
                            Dexterity = 10,
                            FortitudeSave = 6,
                            Initiative = 1,
                            Intelligence = 8,
                            Level = 1,
                            Name = "Orog le Montagnard",
                            PVCurrent = 16,
                            PVMax = 16,
                            RaceId = 12,
                            ReflexeSave = 1,
                            Speed = 30,
                            Strength = 19,
                            UserId = 4,
                            WillpowerSave = 1,
                            Wisdom = 12,
                            XP = 50
                        },
                        new
                        {
                            Id = 30,
                            BaseAttackBonus = 1,
                            CampagnId = 1,
                            Charisma = 14,
                            Constitution = 12,
                            Defence = 15,
                            Dexterity = 19,
                            FortitudeSave = 2,
                            Initiative = 4,
                            Intelligence = 11,
                            Level = 1,
                            Name = "Mew-Mew la Agile",
                            PVCurrent = 11,
                            PVMax = 11,
                            RaceId = 10,
                            ReflexeSave = 6,
                            Speed = 40,
                            Strength = 10,
                            UserId = 1,
                            WillpowerSave = 1,
                            Wisdom = 12,
                            XP = 1
                        },
                        new
                        {
                            Id = 31,
                            BaseAttackBonus = 1,
                            Charisma = 8,
                            Constitution = 13,
                            Defence = 14,
                            Dexterity = 17,
                            FortitudeSave = 1,
                            Initiative = 3,
                            Intelligence = 14,
                            Level = 1,
                            Name = "Vark l'Espion",
                            PVCurrent = 9,
                            PVMax = 9,
                            RaceId = 13,
                            ReflexeSave = 5,
                            Speed = 30,
                            Strength = 8,
                            UserId = 2,
                            WillpowerSave = 3,
                            Wisdom = 12,
                            XP = 1
                        },
                        new
                        {
                            Id = 32,
                            BaseAttackBonus = 1,
                            CampagnId = 2,
                            Charisma = 8,
                            Constitution = 17,
                            Defence = 16,
                            Dexterity = 12,
                            FortitudeSave = 5,
                            Initiative = 1,
                            Intelligence = 10,
                            Level = 1,
                            Name = "Sss'Kala",
                            PVCurrent = 14,
                            PVMax = 14,
                            RaceId = 14,
                            ReflexeSave = 2,
                            Speed = 30,
                            Strength = 14,
                            UserId = 3,
                            WillpowerSave = 3,
                            Wisdom = 13,
                            XP = 1
                        },
                        new
                        {
                            Id = 33,
                            BaseAttackBonus = 1,
                            CampagnId = 1,
                            Charisma = 11,
                            Constitution = 14,
                            Defence = 14,
                            Dexterity = 14,
                            FortitudeSave = 4,
                            Initiative = 2,
                            Intelligence = 9,
                            Level = 1,
                            Name = "Hark l'Imposant",
                            PVCurrent = 13,
                            PVMax = 13,
                            RaceId = 17,
                            ReflexeSave = 3,
                            Speed = 30,
                            Strength = 18,
                            UserId = 4,
                            WillpowerSave = 1,
                            Wisdom = 10,
                            XP = 20
                        },
                        new
                        {
                            Id = 34,
                            BaseAttackBonus = 1,
                            CampagnId = 2,
                            Charisma = 12,
                            Constitution = 12,
                            Defence = 15,
                            Dexterity = 18,
                            FortitudeSave = 1,
                            Initiative = 4,
                            Intelligence = 10,
                            Level = 1,
                            Name = "Meepo le Chanceux",
                            PVCurrent = 7,
                            PVMax = 7,
                            RaceId = 18,
                            ReflexeSave = 5,
                            Speed = 30,
                            Strength = 6,
                            UserId = 1,
                            WillpowerSave = 1,
                            Wisdom = 8,
                            XP = 1
                        },
                        new
                        {
                            Id = 35,
                            BaseAttackBonus = 1,
                            CampagnId = 3,
                            Charisma = 8,
                            Constitution = 18,
                            Defence = 17,
                            Dexterity = 10,
                            FortitudeSave = 6,
                            Initiative = 1,
                            Intelligence = 12,
                            Level = 1,
                            Name = "Xiloscient",
                            PVCurrent = 15,
                            PVMax = 15,
                            RaceId = 4,
                            ReflexeSave = 1,
                            Speed = 25,
                            Strength = 14,
                            UserId = 2,
                            WillpowerSave = 3,
                            Wisdom = 14,
                            XP = 1
                        },
                        new
                        {
                            Id = 36,
                            BaseAttackBonus = 1,
                            Charisma = 15,
                            Constitution = 12,
                            Defence = 12,
                            Dexterity = 13,
                            FortitudeSave = 1,
                            Initiative = 1,
                            Intelligence = 19,
                            Level = 1,
                            Name = "Sylas le Savant",
                            PVCurrent = 10,
                            PVMax = 10,
                            RaceId = 19,
                            ReflexeSave = 2,
                            Speed = 30,
                            Strength = 8,
                            UserId = 3,
                            WillpowerSave = 4,
                            Wisdom = 14,
                            XP = 1
                        },
                        new
                        {
                            Id = 37,
                            BaseAttackBonus = 1,
                            CampagnId = 1,
                            Charisma = 8,
                            Constitution = 16,
                            Defence = 15,
                            Dexterity = 10,
                            FortitudeSave = 5,
                            Initiative = 1,
                            Intelligence = 10,
                            Level = 1,
                            Name = "Pebble",
                            PVCurrent = 14,
                            PVMax = 14,
                            RaceId = 20,
                            ReflexeSave = 1,
                            Speed = 30,
                            Strength = 17,
                            UserId = 4,
                            WillpowerSave = 1,
                            Wisdom = 11,
                            XP = 1
                        },
                        new
                        {
                            Id = 38,
                            BaseAttackBonus = 1,
                            CampagnId = 3,
                            Charisma = 12,
                            Constitution = 14,
                            Defence = 13,
                            Dexterity = 14,
                            FortitudeSave = 3,
                            Initiative = 2,
                            Intelligence = 17,
                            Level = 1,
                            Name = "Ignis",
                            PVCurrent = 11,
                            PVMax = 11,
                            RaceId = 21,
                            ReflexeSave = 3,
                            Speed = 30,
                            Strength = 10,
                            UserId = 1,
                            WillpowerSave = 1,
                            Wisdom = 10,
                            XP = 1
                        },
                        new
                        {
                            Id = 39,
                            BaseAttackBonus = 1,
                            CampagnId = 2,
                            Charisma = 18,
                            Constitution = 11,
                            Defence = 14,
                            Dexterity = 16,
                            FortitudeSave = 1,
                            Initiative = 3,
                            Intelligence = 10,
                            Level = 1,
                            Name = "Pan le Joyeux",
                            PVCurrent = 12,
                            PVMax = 12,
                            RaceId = 22,
                            ReflexeSave = 4,
                            Speed = 35,
                            Strength = 12,
                            UserId = 2,
                            WillpowerSave = 2,
                            Wisdom = 12,
                            XP = 5
                        },
                        new
                        {
                            Id = 40,
                            BaseAttackBonus = 1,
                            CampagnId = 1,
                            Charisma = 10,
                            Constitution = 15,
                            Defence = 18,
                            Dexterity = 8,
                            FortitudeSave = 4,
                            Initiative = 1,
                            Intelligence = 10,
                            Level = 1,
                            Name = "Shelly la Lente",
                            PVCurrent = 13,
                            PVMax = 13,
                            RaceId = 23,
                            ReflexeSave = 1,
                            Speed = 30,
                            Strength = 15,
                            UserId = 3,
                            WillpowerSave = 5,
                            Wisdom = 17,
                            XP = 1
                        },
                        new
                        {
                            Id = 41,
                            BaseAttackBonus = 1,
                            Charisma = 12,
                            Constitution = 14,
                            Defence = 15,
                            Dexterity = 12,
                            FortitudeSave = 4,
                            Initiative = 1,
                            Intelligence = 16,
                            Level = 1,
                            Name = "Korth le Cruel",
                            PVCurrent = 12,
                            PVMax = 12,
                            RaceId = 16,
                            ReflexeSave = 2,
                            Speed = 30,
                            Strength = 14,
                            UserId = 4,
                            WillpowerSave = 1,
                            Wisdom = 10,
                            XP = 1
                        },
                        new
                        {
                            Id = 42,
                            BaseAttackBonus = 1,
                            Charisma = 14,
                            Constitution = 13,
                            Defence = 16,
                            Dexterity = 19,
                            FortitudeSave = 2,
                            Initiative = 4,
                            Intelligence = 10,
                            Level = 1,
                            Name = "Finn le Petit",
                            PVCurrent = 9,
                            PVMax = 9,
                            RaceId = 5,
                            ReflexeSave = 6,
                            Speed = 25,
                            Strength = 8,
                            UserId = 1,
                            WillpowerSave = 2,
                            Wisdom = 12,
                            XP = 1
                        },
                        new
                        {
                            Id = 43,
                            BaseAttackBonus = 1,
                            CampagnId = 1,
                            Charisma = 11,
                            Constitution = 14,
                            Defence = 13,
                            Dexterity = 8,
                            FortitudeSave = 4,
                            Initiative = 1,
                            Intelligence = 10,
                            Level = 1,
                            Name = "Durn le Sage",
                            PVCurrent = 12,
                            PVMax = 12,
                            RaceId = 11,
                            ReflexeSave = 1,
                            Speed = 30,
                            Strength = 16,
                            UserId = 2,
                            WillpowerSave = 6,
                            Wisdom = 18,
                            XP = 1
                        });
                });

            modelBuilder.Entity("WorkGroup_RPGHelp.DL.Entities.Race", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BonusRacialId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("TravelSpeed")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BonusRacialId")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Race", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BonusRacialId = 1,
                            Name = "Elf",
                            TravelSpeed = 0
                        },
                        new
                        {
                            Id = 2,
                            BonusRacialId = 2,
                            Name = "Orc",
                            TravelSpeed = 0
                        },
                        new
                        {
                            Id = 3,
                            BonusRacialId = 3,
                            Name = "Half Elf",
                            TravelSpeed = 0
                        },
                        new
                        {
                            Id = 4,
                            BonusRacialId = 16,
                            Name = "Dwarf",
                            TravelSpeed = 0
                        },
                        new
                        {
                            Id = 5,
                            BonusRacialId = 7,
                            Name = "Halfling",
                            TravelSpeed = 0
                        },
                        new
                        {
                            Id = 6,
                            BonusRacialId = 4,
                            Name = "Dragonborn",
                            TravelSpeed = 0
                        },
                        new
                        {
                            Id = 7,
                            BonusRacialId = 9,
                            Name = "Gnome",
                            TravelSpeed = 0
                        },
                        new
                        {
                            Id = 8,
                            BonusRacialId = 18,
                            Name = "Tiefling",
                            TravelSpeed = 0
                        },
                        new
                        {
                            Id = 9,
                            BonusRacialId = 22,
                            Name = "Half-Orc",
                            TravelSpeed = 0
                        },
                        new
                        {
                            Id = 10,
                            BonusRacialId = 15,
                            Name = "Tabaxi",
                            TravelSpeed = 0
                        },
                        new
                        {
                            Id = 11,
                            BonusRacialId = 5,
                            Name = "Firbolg",
                            TravelSpeed = 0
                        },
                        new
                        {
                            Id = 12,
                            BonusRacialId = 19,
                            Name = "Goliath",
                            TravelSpeed = 0
                        },
                        new
                        {
                            Id = 13,
                            BonusRacialId = 20,
                            Name = "Kenku",
                            TravelSpeed = 0
                        },
                        new
                        {
                            Id = 14,
                            BonusRacialId = 10,
                            Name = "Lizardfolk",
                            TravelSpeed = 0
                        },
                        new
                        {
                            Id = 15,
                            BonusRacialId = 11,
                            Name = "Aasimar",
                            TravelSpeed = 0
                        },
                        new
                        {
                            Id = 16,
                            BonusRacialId = 13,
                            Name = "Hobgoblin",
                            TravelSpeed = 0
                        },
                        new
                        {
                            Id = 17,
                            BonusRacialId = 14,
                            Name = "Bugbear",
                            TravelSpeed = 0
                        },
                        new
                        {
                            Id = 18,
                            BonusRacialId = 23,
                            Name = "Kobold",
                            TravelSpeed = 0
                        },
                        new
                        {
                            Id = 19,
                            BonusRacialId = 21,
                            Name = "Yuan-ti",
                            TravelSpeed = 0
                        },
                        new
                        {
                            Id = 20,
                            BonusRacialId = 8,
                            Name = "Genasi (Earth)",
                            TravelSpeed = 0
                        },
                        new
                        {
                            Id = 21,
                            BonusRacialId = 12,
                            Name = "Genasi (Fire)",
                            TravelSpeed = 0
                        },
                        new
                        {
                            Id = 22,
                            BonusRacialId = 6,
                            Name = "Satyr",
                            TravelSpeed = 0
                        },
                        new
                        {
                            Id = 23,
                            BonusRacialId = 17,
                            Name = "Tortle",
                            TravelSpeed = 0
                        });
                });

            modelBuilder.Entity("WorkGroup_RPGHelp.DL.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "User"
                        });
                });

            modelBuilder.Entity("WorkGroup_RPGHelp.DL.Entities.Spell", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Spell", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A bolt of flame shoots from your fingertips, searing your target.\r\nDamage: 1d10 fire damage (scales with level)",
                            Level = 0,
                            Name = "Firebolt"
                        },
                        new
                        {
                            Id = 2,
                            Description = "A spear of pure shadow pierces a single enemy, ignoring armor.\r\nDamage: 2d8 necrotic damage, ignores non-magical defense.",
                            Level = 0,
                            Name = "Shadow Lance"
                        },
                        new
                        {
                            Id = 3,
                            Description = "A shimmering barrier of force surrounds you.\r\n+5 AC until the start of your next turn.",
                            Level = 0,
                            Name = "Shielding Ward"
                        });
                });

            modelBuilder.Entity("WorkGroup_RPGHelp.DL.Entities.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("User_", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "fabian@test.com",
                            Password = "$argon2id$v=19$m=65536,t=3,p=1$LHZG57rDMJ+sJvIkpI3Jqw$XXx4Ov08UZCFXAOoP+kZTmpI9MVfnJkZ5lP77JNgt/s"
                        },
                        new
                        {
                            Id = 2,
                            Email = "mathieu@test.com",
                            Password = "$argon2id$v=19$m=65536,t=3,p=1$LHZG57rDMJ+sJvIkpI3Jqw$XXx4Ov08UZCFXAOoP+kZTmpI9MVfnJkZ5lP77JNgt/s"
                        },
                        new
                        {
                            Id = 3,
                            Email = "user@example.com",
                            Password = "$argon2id$v=19$m=65536,t=3,p=1$LHZG57rDMJ+sJvIkpI3Jqw$XXx4Ov08UZCFXAOoP+kZTmpI9MVfnJkZ5lP77JNgt/s"
                        },
                        new
                        {
                            Id = 4,
                            Email = "brandt.fabian@gmail.com",
                            Password = "$argon2id$v=19$m=65536,t=3,p=1$LHZG57rDMJ+sJvIkpI3Jqw$XXx4Ov08UZCFXAOoP+kZTmpI9MVfnJkZ5lP77JNgt/s"
                        });
                });

            modelBuilder.Entity("CampagnUsers", b =>
                {
                    b.HasOne("WorkGroup_RPGHelp.DL.Entities.Campagn", null)
                        .WithMany()
                        .HasForeignKey("CampagnsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkGroup_RPGHelp.DL.Entities.Users", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RaceSpell", b =>
                {
                    b.HasOne("WorkGroup_RPGHelp.DL.Entities.Race", null)
                        .WithMany()
                        .HasForeignKey("RacesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkGroup_RPGHelp.DL.Entities.Spell", null)
                        .WithMany()
                        .HasForeignKey("SpellsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RoleUsers", b =>
                {
                    b.HasOne("WorkGroup_RPGHelp.DL.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkGroup_RPGHelp.DL.Entities.Users", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WorkGroup_RPGHelp.DL.Entities.Charactere", b =>
                {
                    b.HasOne("WorkGroup_RPGHelp.DL.Entities.Campagn", "Campagns")
                        .WithMany("Characteres")
                        .HasForeignKey("CampagnId");

                    b.HasOne("WorkGroup_RPGHelp.DL.Entities.Race", "Race")
                        .WithMany()
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkGroup_RPGHelp.DL.Entities.Users", "Users")
                        .WithMany("Characteres")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campagns");

                    b.Navigation("Race");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("WorkGroup_RPGHelp.DL.Entities.Race", b =>
                {
                    b.HasOne("WorkGroup_RPGHelp.DL.Entities.BonusRacial", "BonusRacial")
                        .WithOne("Race")
                        .HasForeignKey("WorkGroup_RPGHelp.DL.Entities.Race", "BonusRacialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BonusRacial");
                });

            modelBuilder.Entity("WorkGroup_RPGHelp.DL.Entities.BonusRacial", b =>
                {
                    b.Navigation("Race")
                        .IsRequired();
                });

            modelBuilder.Entity("WorkGroup_RPGHelp.DL.Entities.Campagn", b =>
                {
                    b.Navigation("Characteres");
                });

            modelBuilder.Entity("WorkGroup_RPGHelp.DL.Entities.Users", b =>
                {
                    b.Navigation("Characteres");
                });
#pragma warning restore 612, 618
        }
    }
}
