// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorkGroup_RPGHelp.DAL.Contexts;

#nullable disable

namespace WorkGroup_RPGHelp.DAL.Migrations
{
    [DbContext(typeof(RPGHelpContext))]
    [Migration("20251016111413_Add Race")]
    partial class AddRace
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RoleUsers", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("RoleId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("RoleUsers");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            UserId = 1
                        },
                        new
                        {
                            RoleId = 2,
                            UserId = 1
                        },
                        new
                        {
                            RoleId = 3,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("WorkGroup_RPGHelp.DL.Entities.BonusRacial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Bonus")
                        .HasColumnType("int");

                    b.Property<int>("Malus")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("BonusRacial", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bonus = 2,
                            Malus = -2,
                            Name = "Dexterity",
                            Name2 = "Strength"
                        },
                        new
                        {
                            Id = 2,
                            Bonus = 2,
                            Malus = -2,
                            Name = "Intelligence",
                            Name2 = "Strength"
                        },
                        new
                        {
                            Id = 3,
                            Bonus = 2,
                            Malus = -2,
                            Name = "Constitution",
                            Name2 = "Charisma"
                        });
                });

            modelBuilder.Entity("WorkGroup_RPGHelp.DL.Entities.Campagn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Campagn", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Ma première Campagne"
                        },
                        new
                        {
                            Id = 2,
                            Name = "True Story"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Dragon First"
                        });
                });

            modelBuilder.Entity("WorkGroup_RPGHelp.DL.Entities.Race", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BonusRacialId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("TravelSpeed")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BonusRacialId")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Race", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BonusRacialId = 1,
                            Name = "Elf",
                            TravelSpeed = 0
                        },
                        new
                        {
                            Id = 2,
                            BonusRacialId = 2,
                            Name = "Orc",
                            TravelSpeed = 0
                        },
                        new
                        {
                            Id = 3,
                            BonusRacialId = 3,
                            Name = "Half Elf",
                            TravelSpeed = 0
                        });
                });

            modelBuilder.Entity("WorkGroup_RPGHelp.DL.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "GM"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Players"
                        });
                });

            modelBuilder.Entity("WorkGroup_RPGHelp.DL.Entities.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("User_", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "fabian@test.com",
                            Password = ""
                        },
                        new
                        {
                            Id = 2,
                            Email = "mathieu@test.com",
                            Password = ""
                        });
                });

            modelBuilder.Entity("RoleUsers", b =>
                {
                    b.HasOne("WorkGroup_RPGHelp.DL.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkGroup_RPGHelp.DL.Entities.Users", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WorkGroup_RPGHelp.DL.Entities.Race", b =>
                {
                    b.HasOne("WorkGroup_RPGHelp.DL.Entities.BonusRacial", "BonusRacial")
                        .WithOne("Race")
                        .HasForeignKey("WorkGroup_RPGHelp.DL.Entities.Race", "BonusRacialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BonusRacial");
                });

            modelBuilder.Entity("WorkGroup_RPGHelp.DL.Entities.BonusRacial", b =>
                {
                    b.Navigation("Race")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
